### ISSUE TITLE
ワークフローをAWS SDK for JavaScript (v3)に移行

### ISSUE THREAD

**Issue by YamabikoLab** [YamabikoLab/laravel-best-practices#17]
https://github.com/actions/setup-node

```
name: Deploy Lambda Function

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_LAMBDA_FUNCTION_NAME: my-lambda-function
  AWS_LAMBDA_ROLE_ARN: arn:aws:iam::123456789012:role/lambda-role

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Deploy Lambda function
      run: npx aws-sdk deploy --region ${{ env.AWS_REGION }} --function-name ${{ env.AWS_LAMBDA_FUNCTION_NAME }} --role ${{ env.AWS_LAMBDA_ROLE_ARN }} --handler index.handler --zip-file fileb://index.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

```
